import { Document } from "@/lib/types";

export const mockDocuments: Document[] = [
  {
    id: "doc-001",
    title: "Samsung Galaxy S25 Receipt",
    type: "image",
    category: "Purchase",
    subcategory: "Electronics",
    documentDate: "2026-08-12",
    uploadedAt: "2026-08-14T10:30:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 79999,
    entities: [
      { id: "ent-001", type: "product", label: "Product", value: "Samsung Galaxy S25" },
      { id: "ent-002", type: "amount", label: "Amount", value: "₹79,999" },
      { id: "ent-003", type: "date", label: "Purchase Date", value: "12 Aug 2026" },
      { id: "ent-004", type: "date", label: "Warranty Until", value: "12 Aug 2027" },
      { id: "ent-005", type: "organization", label: "Merchant", value: "Croma Electronics" },
    ],
    relatedDocumentIds: ["doc-002"],
    description: "Purchase receipt for Samsung Galaxy S25 from Croma Electronics, MG Road",
  },
  {
    id: "doc-002",
    title: "Samsung Galaxy S25 Warranty Card",
    type: "image",
    category: "Warranty",
    documentDate: "2026-08-12",
    uploadedAt: "2026-08-14T10:35:00Z",
    status: "ready",
    duplicateStatus: "none",
    entities: [
      { id: "ent-006", type: "product", label: "Product", value: "Samsung Galaxy S25" },
      { id: "ent-007", type: "date", label: "Warranty Start", value: "12 Aug 2026" },
      { id: "ent-008", type: "date", label: "Warranty End", value: "12 Aug 2027" },
      { id: "ent-009", type: "organization", label: "Manufacturer", value: "Samsung India" },
    ],
    relatedDocumentIds: ["doc-001"],
    description: "Standard 1-year manufacturer warranty for Samsung Galaxy S25",
  },
  {
    id: "doc-003",
    title: "Dell Inspiron 15 Purchase Invoice",
    type: "pdf",
    category: "Purchase",
    subcategory: "Electronics",
    documentDate: "2024-03-15",
    uploadedAt: "2024-03-16T14:20:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 72000,
    entities: [
      { id: "ent-010", type: "product", label: "Product", value: "Dell Inspiron 15 3520" },
      { id: "ent-011", type: "amount", label: "Amount", value: "₹72,000" },
      { id: "ent-012", type: "date", label: "Purchase Date", value: "15 Mar 2024" },
      { id: "ent-013", type: "date", label: "Warranty Until", value: "15 Mar 2026" },
      { id: "ent-014", type: "organization", label: "Seller", value: "Dell India Online Store" },
      { id: "ent-015", type: "invoice_number", label: "Invoice", value: "INV-DL-2024-78542" },
    ],
    relatedDocumentIds: ["doc-004", "doc-005"],
    description: "Purchase invoice for Dell Inspiron 15 3520 laptop from Dell India online store",
  },
  {
    id: "doc-004",
    title: "Dell Laptop Screen Repair Invoice",
    type: "image",
    category: "Repair",
    documentDate: "2025-06-20",
    uploadedAt: "2025-06-22T09:15:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 8000,
    entities: [
      { id: "ent-016", type: "product", label: "Product", value: "Dell Inspiron 15 3520" },
      { id: "ent-017", type: "amount", label: "Repair Cost", value: "₹8,000" },
      { id: "ent-018", type: "date", label: "Repair Date", value: "20 Jun 2025" },
      { id: "ent-019", type: "organization", label: "Service Center", value: "Laptop Care Solutions" },
      { id: "ent-020", type: "product", label: "Issue", value: "Screen replacement" },
    ],
    relatedDocumentIds: ["doc-003", "doc-005"],
    description: "Screen replacement repair at Laptop Care Solutions, Koramangala",
  },
  {
    id: "doc-005",
    title: "Dell Laptop Keyboard Repair Invoice",
    type: "image",
    category: "Repair",
    documentDate: "2026-08-28",
    uploadedAt: "2026-08-30T16:45:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 18000,
    entities: [
      { id: "ent-021", type: "product", label: "Product", value: "Dell Inspiron 15 3520" },
      { id: "ent-022", type: "amount", label: "Repair Cost", value: "₹18,000" },
      { id: "ent-023", type: "date", label: "Repair Date", value: "28 Aug 2026" },
      { id: "ent-024", type: "organization", label: "Service Center", value: "Dell Authorized Service" },
      { id: "ent-025", type: "product", label: "Issue", value: "Keyboard + touchpad replacement" },
    ],
    relatedDocumentIds: ["doc-003", "doc-004"],
    description: "Keyboard and touchpad replacement at Dell Authorized Service Center",
  },
  {
    id: "doc-006",
    title: "Apollo Pharmacy Bill",
    type: "image",
    category: "Medical",
    documentDate: "2026-08-05",
    uploadedAt: "2026-08-05T18:30:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 1240,
    entities: [
      { id: "ent-026", type: "organization", label: "Pharmacy", value: "Apollo Pharmacy" },
      { id: "ent-027", type: "amount", label: "Amount", value: "₹1,240" },
      { id: "ent-028", type: "date", label: "Bill Date", value: "05 Aug 2026" },
      { id: "ent-029", type: "location", label: "Branch", value: "Indiranagar, Bangalore" },
    ],
    relatedDocumentIds: [],
    description: "Monthly prescription medicines from Apollo Pharmacy",
  },
  {
    id: "doc-007",
    title: "MedPlus Pharmacy Receipt",
    type: "image",
    category: "Medical",
    documentDate: "2026-08-18",
    uploadedAt: "2026-08-18T11:00:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 2000,
    entities: [
      { id: "ent-030", type: "organization", label: "Pharmacy", value: "MedPlus" },
      { id: "ent-031", type: "amount", label: "Amount", value: "₹2,000" },
      { id: "ent-032", type: "date", label: "Bill Date", value: "18 Aug 2026" },
    ],
    relatedDocumentIds: [],
    description: "Over-the-counter medicines and health supplements",
  },
  {
    id: "doc-008",
    title: "Electricity Bill - August 2026",
    type: "pdf",
    category: "Finance",
    subcategory: "Payment",
    documentDate: "2026-08-01",
    uploadedAt: "2026-08-03T09:00:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 2350,
    entities: [
      { id: "ent-033", type: "organization", label: "Provider", value: "BESCOM" },
      { id: "ent-034", type: "amount", label: "Amount", value: "₹2,350" },
      { id: "ent-035", type: "date", label: "Bill Date", value: "01 Aug 2026" },
      { id: "ent-036", type: "date", label: "Due Date", value: "15 Sep 2026" },
      { id: "ent-037", type: "invoice_number", label: "Consumer No.", value: "BNG-4521-8897" },
    ],
    relatedDocumentIds: [],
    description: "BESCOM electricity bill for August 2026",
  },
  {
    id: "doc-009",
    title: "HDFC Mutual Fund Statement",
    type: "pdf",
    category: "Finance",
    subcategory: "Investment",
    documentDate: "2026-08-25",
    uploadedAt: "2026-08-26T08:00:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 5000,
    entities: [
      { id: "ent-038", type: "organization", label: "Fund House", value: "HDFC AMC" },
      { id: "ent-039", type: "investment_type", label: "Type", value: "Mutual Fund" },
      { id: "ent-040", type: "product", label: "Fund", value: "HDFC Bluechip Fund" },
      { id: "ent-041", type: "amount", label: "SIP Amount", value: "₹5,000" },
      { id: "ent-042", type: "date", label: "Statement Date", value: "25 Aug 2026" },
    ],
    relatedDocumentIds: [],
    description: "Monthly SIP statement for HDFC Bluechip Fund",
  },
  {
    id: "doc-010",
    title: "Health Insurance Policy - Star Health",
    type: "pdf",
    category: "Documents",
    subcategory: "Insurance",
    documentDate: "2026-04-01",
    uploadedAt: "2026-04-02T12:00:00Z",
    status: "ready",
    duplicateStatus: "none",
    amount: 15000,
    entities: [
      { id: "ent-043", type: "organization", label: "Insurer", value: "Star Health Insurance" },
      { id: "ent-044", type: "amount", label: "Premium", value: "₹15,000" },
      { id: "ent-045", type: "date", label: "Policy Start", value: "01 Apr 2026" },
      { id: "ent-046", type: "date", label: "Policy End", value: "31 Mar 2027" },
      { id: "ent-047", type: "product", label: "Plan", value: "Star Comprehensive" },
    ],
    relatedDocumentIds: [],
    description: "Annual health insurance policy from Star Health Insurance",
  },
  {
    id: "doc-011",
    title: "Gym Membership Receipt",
    type: "image",
    category: "Subscriptions",
    documentDate: "2026-07-01",
    uploadedAt: "2026-07-02T10:00:00Z",
    status: "ready",
    duplicateStatus: "possible",
    amount: 12000,
    entities: [
      { id: "ent-048", type: "organization", label: "Gym", value: "Cult.fit HSR Layout" },
      { id: "ent-049", type: "amount", label: "Amount", value: "₹12,000" },
      { id: "ent-050", type: "date", label: "Start Date", value: "01 Jul 2026" },
      { id: "ent-051", type: "date", label: "End Date", value: "31 Dec 2026" },
    ],
    relatedDocumentIds: [],
    description: "6-month gym membership at Cult.fit HSR Layout",
  },
];
